export const ApiPricingPlans = [
  {
    name: "Pay-as-you-go",
    description: "No commitment, billed monthly on actual usage",
    volume: "Any",
    price: "$0.40",
    period: "/ scan",
    cta: "Get started",
    features: [
      "No minimum commitment",
      "Pay for what you use",
      "Full API access",
    ],
  },
  {
    name: "API Starter",
    description: "Perfect for small projects and startups",
    volume: "Up to 5,000",
    price: "$1,925",
    period: "/ mo",
    ratePerScan: "$0.39 / scan",
    cta: "Get in touch",
    features: [
      "Up to 5,000 scans/month",
      "Full documentation",
      "Sandbox access",
      "Webhook support",
    ],
  },
  {
    name: "API Growth",
    description: "For growing businesses and teams",
    volume: "Up to 25,000",
    price: "$9,125",
    period: "/ mo",
    ratePerScan: "$0.37 / scan",
    cta: "Get in touch",
    features: [
      "Up to 25,000 scans/month",
      "Advanced reporting",
      "Priority support",
      "Webhook support",
    ],
  },
  {
    name: "API Scale",
    description: "For high-volume applications",
    volume: "Up to 100,000",
    price: "$36,000",
    period: "/ mo",
    ratePerScan: "$0.36 / scan",
    cta: "Contact sales",
    features: [
      "Up to 100,000 scans/month",
      "Dedicated support",
      "Custom integrations",
      "SLA guarantees",
    ],
  },
  {
    name: "API Enterprise (Direct)",
    description: "For enterprise-scale deployments",
    volume: "100,000+",
    price: "Custom",
    ratePerScan: "$0.35 / scan (floor)",
    cta: "Contact sales",
    features: [
      "Unlimited scans",
      "12-month minimum contract",
      "Direct sales support",
      "No channel commission",
      "Custom pricing",
    ],
  },
];
