import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import EnterpriseHeader from "@/components/enterprise/EnterpriseHeader";
import EnterpriseFooter from "@/components/enterprise/EnterpriseFooter";

/** Deeptrack enterprise due-diligence design: consultation-led commercial pathway, with no public rate, duration, SLA, or delivery-outcome claims. */
export const metadata: Metadata = { title: "Enterprise Engagements", description: "Engagement pathways for enterprise identity, media, and AI evidence due diligence.", alternates: { canonical: "/engagements" } };
const engagements = [["Diagnostic", "Map one consequential workflow, its evidence, decision owners, and escalation points."], ["Advisory", "Develop a practical evidence-assessment and governance approach for a priority business area."], ["Prototype & build", "Design and implement an initial diligence workflow around defined evidence and operating constraints."], ["Production hardening", "Strengthen ownership, documentation, integration, and operational readiness for an existing workflow."], ["Training", "Equip relevant teams with a shared approach to evidence, review, escalation, and decision records."], ["Research", "Explore an evidence-integrity question where applied research can inform an operating decision."]];
export default function EngagementsPage() { return <div className="min-h-screen bg-white text-[#333333]"><EnterpriseHeader /><main><section className="bg-[#333333] text-white"><div className="mx-auto max-w-[1100px] px-5 py-20 lg:px-10 lg:py-28"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#99D3F0]">Enterprise engagements</p><h1 className="mt-6 max-w-4xl font-[family-name:var(--font-space-grotesk)] text-5xl font-medium tracking-[-0.06em] sm:text-6xl">Bring the right level of diligence to the decision in front of you.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[#CCE9F8]">Deeptrack scopes work around the evidence, operating context, and decision requirement—not a generic pricing tier.</p></div></section><section className="mx-auto max-w-[1100px] px-5 py-20 lg:px-10"><div className="grid border-t border-[#CCE9F8] md:grid-cols-2 xl:grid-cols-3">{engagements.map(([title, body], index) => <article key={title} className="min-h-64 border-b border-[#CCE9F8] py-8 pr-8 md:border-r md:px-7 xl:nth-[3n]:border-r-0"><span className="text-sm text-[#0191DA]">0{index + 1}</span><h2 className="mt-8 font-[family-name:var(--font-space-grotesk)] text-2xl font-medium">{title}</h2><p className="mt-4 text-sm leading-6 text-[#808080]">{body}</p></article>)}</div></section><section className="bg-[#E6F4FB]"><div className="mx-auto grid max-w-[1100px] gap-10 px-5 py-20 lg:grid-cols-[.85fr_1.15fr] lg:px-10"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#0191DA]">Commercial approach</p><h2 className="mt-4 font-[family-name:var(--font-space-grotesk)] text-4xl font-medium tracking-[-0.05em]">A proposal based on the work that is actually needed.</h2></div><div className="grid gap-4 sm:grid-cols-2">{["Contact us for a tailored proposal", "Timeline scoped per engagement", "Scope anchored to a defined decision or workflow", "No public rate card, credit volume, or SLA promise"].map((item) => <p key={item} className="flex gap-3 bg-white p-5 text-sm leading-6"><Check className="mt-1 shrink-0 text-[#0191DA]" size={16} />{item}</p>)}</div></div></section><section className="mx-auto max-w-[1100px] px-5 py-20 text-center lg:px-10"><h2 className="font-[family-name:var(--font-space-grotesk)] text-4xl font-medium tracking-[-0.05em]">Tell us what decision needs to be more defensible.</h2><Link href="/contact" className="mt-8 inline-flex items-center gap-2 bg-[#0191DA] px-5 py-4 text-sm font-semibold text-white hover:bg-[#34A7E1]">Contact us for a tailored proposal <ArrowRight size={17} /></Link></section></main><EnterpriseFooter /></div>; }
