import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpen, FileSearch, Scale } from "lucide-react";
import EnterpriseHeader from "@/components/enterprise/EnterpriseHeader";
import EnterpriseFooter from "@/components/enterprise/EnterpriseFooter";

/** Deeptrack enterprise due-diligence design: applied research hub with no invented publication volume, frequency, or outcome claims. */
export const metadata: Metadata = { title: "Research & Due-Diligence Intelligence", description: "Applied research and intelligence for identity, media, document, and AI-generated evidence in high-consequence workflows.", alternates: { canonical: "/research" } };
const themes = [[BookOpen, "Evidence integrity", "How provenance, context, manipulation risk, and review practice affect the reliability of digital evidence."], [FileSearch, "Decision workflows", "How teams can connect evidence assessment to ownership, escalation, and a documented disposition."], [Scale, "Governance and accountability", "How enterprise, public-sector, financial-services, media, and insurance teams can frame responsibility around evidence-led decisions."]];
export default function ResearchPage() { return <div className="min-h-screen bg-white text-[#333333]"><EnterpriseHeader /><main><section className="bg-[#F2F9FD]"><div className="mx-auto max-w-[1180px] px-5 py-20 lg:px-10 lg:py-28"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#0191DA]">Research & intelligence</p><h1 className="mt-6 max-w-5xl font-[family-name:var(--font-space-grotesk)] text-5xl font-medium tracking-[-0.06em] sm:text-6xl">Applied research for teams deciding what digital evidence they can rely on.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[#808080]">Deeptrack research connects identity, media, document, and AI-generated evidence questions to the operating decisions that depend on them.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/news" className="inline-flex items-center gap-2 bg-[#0191DA] px-5 py-4 text-sm font-semibold text-white hover:bg-[#34A7E1]">Explore News Center <ArrowRight size={17} /></Link><Link href="/resources/nacha-2026-checklist" className="inline-flex items-center gap-2 border border-[#333333] px-5 py-4 text-sm font-semibold text-[#333333] hover:border-[#0191DA] hover:text-[#0191DA]">View NACHA resource <ArrowRight size={17} /></Link></div></div></section><section className="mx-auto max-w-[1180px] px-5 py-20 lg:px-10"><div className="grid border-t border-[#CCE9F8] md:grid-cols-3">{themes.map(([Icon, title, body], index) => <article key={title as string} className="min-h-72 border-b border-[#CCE9F8] py-8 pr-8 md:border-r md:px-7 last:border-r-0"><span className="text-sm text-[#0191DA]">0{index + 1}</span><Icon className="mt-8 text-[#0191DA]" size={26} strokeWidth={1.7} /><h2 className="mt-5 font-[family-name:var(--font-space-grotesk)] text-2xl font-medium">{title as string}</h2><p className="mt-4 text-sm leading-6 text-[#808080]">{body as string}</p></article>)}</div></section><section className="bg-[#333333] text-white"><div className="mx-auto grid max-w-[1180px] gap-10 px-5 py-20 lg:grid-cols-[.85fr_1.15fr] lg:px-10"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#99D3F0]">For researchers and practitioners</p><h2 className="mt-4 font-[family-name:var(--font-space-grotesk)] text-4xl font-medium tracking-[-0.05em]">Turn intelligence into a better operating question.</h2></div><p className="text-base leading-7 text-[#CCE9F8]">Research is most useful when it informs a clear question: what evidence matters, what decision depends on it, who owns review, and what record should remain after the decision is made.</p></div></section></main><EnterpriseFooter /></div>; }
