export const pricingPlans = [
  {
    name: "Trial",
    description: "Free",
    price: "Free",
    cta: "Get in touch",
    features: [
      "20 scan credits",
      "Basic results",
      "30-day access",
      "Email support",
    ],
  },
  {
    name: "Starter",
    description: "For individuals",
    price: "$75",
    period: " /month",
    cta: "Get in touch",
    features: [
      "150 scan credits/month",
      "Advanced analytics",
      "API access",
      "Priority support",
      "Custom branding",
    ],
  },
  {
    name: "Pro",
    description: "Most popular",
    price: "$259",
    period: " /month",
    cta: "Get in touch",
    features: [
      "600 scan credits/month",
      "Real-time dashboards",
      "Webhook integrations",
      "Team collaboration (5 users)",
      "24/7 phone support",
      "Advanced reporting",
    ],
  },
  {
    name: "Business",
    description: "For growing businesses",
    price: "$999",
    period: " /month",
    cta: "Get in touch",
    features: [
      "2,500 scan credits/month",
      "Advanced analytics & reporting",
      "API access & webhooks",
      "Team collaboration (10 users)",
      "Priority 24/7 support",
      "Custom integrations",
      "Bulk scanning tools",
    ],
  },
  {
    name: "Enterprise",
    description: "For large teams",
    price: "Custom",
    cta: "Get in touch",
    features: [
      "Contact Sales",
      "10,000+ scan credits/month",
      "Dedicated account manager",
      "SLA guarantees",
      "Multi-team management",
      "Compliance & audit logs",
      "Custom integrations",
    ],
  },
];
