import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, ChevronDown, Menu } from "lucide-react";

/** Deeptrack enterprise due-diligence design: information-rich navigation on a white canvas using only approved Deeptrack colors. */
type NavItem = { label: string; href: string; external?: boolean };
type NavGroup = { label: string; items: NavItem[] };

const groups: NavGroup[] = [
  { label: "Due diligence", items: [{ label: "Operating model", href: "/due-diligence" }, { label: "Workflow assessment", href: "/assessment" }, { label: "Pricing & engagements", href: "/pricing" }] },
  { label: "Capabilities", items: [{ label: "Image authentication", href: "/solution/image-authentication" }, { label: "Audio authentication", href: "/solution/audio-authentication" }, { label: "Gotham", href: "/solution/gotham" }, { label: "Sentinel", href: "/sentinel" }] },
  { label: "Industries", items: [{ label: "Financial services", href: "/industries/financial-services" }, { label: "Insurance", href: "/industries/insurance" }, { label: "Media houses", href: "/industries/media" }, { label: "Government", href: "/industries/government" }, { label: "Flexible workspaces", href: "/industries/flexible-workspaces" }] },
  { label: "Developers", items: [{ label: "Evidence Assessment API", href: "/productApi" }, { label: "Developer console", href: "/console" }, { label: "Documentation", href: "https://www.deeptrack.io/docs/introduction", external: true }] },
  { label: "Intelligence", items: [{ label: "Research", href: "/research" }, { label: "News Center", href: "/news" }, { label: "NACHA resource", href: "/resources/nacha-2026-checklist" }] },
  { label: "Partners", items: [{ label: "Partner with Deeptrack", href: "/partners" }, { label: "Partner Portal", href: "/portal/login" }] },
  { label: "Company", items: [{ label: "About Deeptrack", href: "/about" }, { label: "Careers", href: "/career" }, { label: "Investor access", href: "/contact?topic=investor" }, { label: "Contact", href: "/contact" }] },
];
function NavDestination({ item, className }: { item: NavItem; className: string }) { return item.external ? <a href={item.href} target="_blank" rel="noreferrer" className={className}>{item.label}<ArrowUpRight size={13} /></a> : <Link href={item.href} className={className}>{item.label}</Link>; }
function GroupLinks({ group, mobile = false }: { group: NavGroup; mobile?: boolean }) { return <div className={mobile ? "mt-3 grid gap-1" : "absolute left-1/2 top-7 z-50 w-60 -translate-x-1/2 border border-[#CCE9F8] bg-white p-3 shadow-sm"}>{!mobile && <p className="px-2 pb-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#0191DA]">{group.label}</p>}{group.items.map((item) => <NavDestination key={item.href} item={item} className={mobile ? "flex items-center gap-2 py-2 text-sm text-[#808080] hover:text-[#0191DA]" : "flex items-center justify-between px-2 py-2 text-xs leading-5 text-[#333333] hover:bg-[#E6F4FB] hover:text-[#0191DA]"} />)}</div>; }

export default function EnterpriseHeader() { return <header className="sticky top-0 z-50 border-b border-[#CCE9F8] bg-white/95 backdrop-blur"><div className="mx-auto flex h-[76px] max-w-[1540px] items-center justify-between gap-5 px-5 lg:px-8"><Link href="/" aria-label="Deeptrack home" className="flex shrink-0 items-center"><Image src="/logos/deeptrack-high-resolution-logo-black-transparent.png" alt="Deeptrack" width={170} height={36} className="h-7 w-auto" priority /></Link><nav className="hidden min-w-0 flex-1 items-center justify-center gap-3 xl:flex" aria-label="Primary navigation">{groups.map((group) => <details key={group.label} className="group relative"><summary className="flex cursor-pointer list-none items-center gap-1 whitespace-nowrap text-[12px] font-medium text-[#333333] marker:content-none hover:text-[#0191DA]">{group.label}<ChevronDown size={13} className="transition-transform group-open:rotate-180" /></summary><GroupLinks group={group} /></details>)}</nav><Link href="/contact" className="hidden shrink-0 items-center gap-2 bg-[#0191DA] px-4 py-3 text-[12px] font-semibold text-white transition-colors hover:bg-[#34A7E1] sm:flex">Request an assessment <ArrowUpRight size={15} /></Link><details className="group relative xl:hidden"><summary className="grid h-10 w-10 cursor-pointer list-none place-items-center text-[#333333] marker:content-none" aria-label="Open navigation"><Menu size={22} /></summary><div className="fixed left-0 right-0 top-[76px] max-h-[calc(100vh-76px)] overflow-y-auto border-t border-[#CCE9F8] bg-white px-5 py-6"><nav className="grid gap-2 lg:grid-cols-2" aria-label="Mobile navigation">{groups.map((group) => <details key={group.label} className="border-b border-[#E6F4FB] py-3"><summary className="flex cursor-pointer list-none items-center justify-between font-[family-name:var(--font-space-grotesk)] text-lg font-medium"><span>{group.label}</span><ChevronDown size={17} /></summary><GroupLinks group={group} mobile /></details>)}</nav><Link href="/contact" className="mt-6 inline-flex items-center gap-2 bg-[#0191DA] px-4 py-3 text-sm font-semibold text-white">Request an assessment <ArrowUpRight size={15} /></Link></div></details></div></header>; }
