import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Linkedin, Twitter } from "lucide-react";

/** Deeptrack enterprise due-diligence design: comprehensive retained-site footer using only approved brand colors and verified destinations. */
type FooterItem = { label: string; href: string; external?: boolean };
const columns: Array<{ title: string; items: FooterItem[] }> = [
  { title: "Due diligence", items: [{ label: "Operating model", href: "/due-diligence" }, { label: "Workflow assessment", href: "/assessment" }, { label: "Pricing & engagements", href: "/pricing" }] },
  { title: "Capabilities", items: [{ label: "Image authentication", href: "/solution/image-authentication" }, { label: "Audio authentication", href: "/solution/audio-authentication" }, { label: "Gotham", href: "/solution/gotham" }, { label: "Sentinel", href: "/sentinel" }] },
  { title: "Industries", items: [{ label: "Financial services", href: "/industries/financial-services" }, { label: "Insurance", href: "/industries/insurance" }, { label: "Media houses", href: "/industries/media" }, { label: "Government", href: "/industries/government" }, { label: "Flexible workspaces", href: "/industries/flexible-workspaces" }] },
  { title: "Developers", items: [{ label: "Evidence Assessment API", href: "/productApi" }, { label: "Developer console", href: "/console" }, { label: "Documentation", href: "https://www.deeptrack.io/docs/introduction", external: true }] },
  { title: "Intelligence", items: [{ label: "Research", href: "/research" }, { label: "News Center", href: "/news" }, { label: "NACHA resource", href: "/resources/nacha-2026-checklist" }] },
  { title: "Partners & company", items: [{ label: "Partner with Deeptrack", href: "/partners" }, { label: "Partner Portal", href: "/portal/login" }, { label: "About", href: "/about" }, { label: "Careers", href: "/career" }, { label: "Investor access", href: "https://investors.deeptrack.io/", external: true }, { label: "Contact", href: "/contact" }] },
  { title: "Legal & trust", items: [{ label: "Trust Center", href: "https://app.eu.vanta.com/deeptrack.io/trust/ykzpe8x33wwv9mki8rjv61", external: true }, { label: "Legal Center", href: "/legal" }, { label: "Privacy Policy", href: "/legal/privacy-policy" }, { label: "Terms of Use", href: "/legal/terms-of-use" }, { label: "Service Level Agreement", href: "/legal/service-level-agreement" }] },
];
function FooterDestination({ item }: { item: FooterItem }) { const className = "text-sm leading-5 text-[#E6F4FB] hover:text-white"; return item.external ? <a href={item.href} target="_blank" rel="noreferrer" className={className}>{item.label}</a> : <Link href={item.href} className={className}>{item.label}</Link>; }
export default function EnterpriseFooter() { return <footer className="bg-[#333333] text-white"><div className="mx-auto max-w-[1540px] px-5 lg:px-8"><section className="grid gap-8 border-b border-[#808080] py-14 lg:grid-cols-[1.2fr_.8fr] lg:py-20"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#99D3F0]">Enterprise due diligence</p><h2 className="mt-4 max-w-2xl font-[family-name:var(--font-space-grotesk)] text-4xl font-medium tracking-[-0.05em]">Bring us the decision before the exposure becomes an event.</h2><p className="mt-5 max-w-xl text-sm leading-6 text-[#CCE9F8]">Start with one workflow where digital evidence affects access, publication, payment, claims, public action, or an operational exception.</p><Link href="/contact" className="mt-7 inline-flex items-center gap-2 bg-[#0191DA] px-5 py-4 text-sm font-semibold text-white hover:bg-[#34A7E1]">Request an assessment <ArrowRight size={16} /></Link></div><div className="border-l-2 border-[#0191DA] pl-6"><Image src="/logos/deeptrack-high-resolution-logo-white-transparent.png" alt="Deeptrack" width={180} height={38} className="h-8 w-auto" /><p className="mt-6 max-w-sm text-sm leading-6 text-[#CCE9F8]">Enterprise due diligence for identity, media, documents, and AI-generated evidence.</p><p className="mt-5 text-sm leading-6 text-[#E6F4FB]">For organisations that need to understand what they can rely on before they act.</p></div></section><section className="grid gap-x-8 gap-y-10 border-b border-[#808080] py-14 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{columns.map((column) => <div key={column.title}><p className="text-[11px] font-semibold uppercase tracking-[0.14em] text-[#99D3F0]">{column.title}</p><div className="mt-5 flex flex-col gap-3">{column.items.map((item) => <FooterDestination item={item} key={item.href} />)}</div></div>)}</section><section className="flex flex-col gap-6 py-7 text-xs text-[#CCE9F8] lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap items-center gap-x-4 gap-y-2"><span>© {new Date().getFullYear()} Deeptrack Inc.</span><span>A due diligence company.</span></div><div className="flex items-center gap-3"><a href="https://x.com/deeptrck" target="_blank" rel="noreferrer" aria-label="Deeptrack on X" className="grid h-9 w-9 place-items-center border border-[#808080] text-[#E6F4FB] hover:border-[#0191DA] hover:text-white"><Twitter size={16} /></a><a href="https://www.linkedin.com/company/deeptrck/" target="_blank" rel="noreferrer" aria-label="Deeptrack on LinkedIn" className="grid h-9 w-9 place-items-center border border-[#808080] text-[#E6F4FB] hover:border-[#0191DA] hover:text-white"><Linkedin size={16} /></a></div></section></div></footer>; }
