import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import EnterpriseHeader from "@/components/enterprise/EnterpriseHeader";
import EnterpriseFooter from "@/components/enterprise/EnterpriseFooter";

/** Deeptrack enterprise due-diligence design: method-first page; no unsupported performance or compliance claims. */
export const metadata: Metadata = { title: "Enterprise Due Diligence | Deeptrack", description: "A decision-ready approach to identity, media, and AI-generated evidence for high-consequence workflows.", alternates: { canonical: "/due-diligence" } };
const steps = [["Map", "Define the decision at risk, the current workflow, ownership, and what failure would mean."], ["Collect", "Identify identity, document, media, provenance, and operational context required for review."], ["Evaluate", "Apply forensic signals, provenance checks, risk context, and defined review criteria."], ["Review", "Route exceptions to the right human owner with clear thresholds and supporting evidence."], ["Document", "Preserve the evidence considered, decision, reviewer disposition, and follow-up action."], ["Monitor", "Use agreed indicators and escalation paths to manage new or recurring risk."]];
export default function DueDiligencePage() { return <div className="min-h-screen bg-white text-[#333333]"><EnterpriseHeader /><main><section className="bg-[#001D2C] text-white"><div className="mx-auto max-w-[1100px] px-5 py-20 lg:px-10 lg:py-28"><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#67BDE9]">The operating model</p><h1 className="mt-6 max-w-4xl font-[family-name:var(--font-space-grotesk)] text-5xl font-medium tracking-[-0.06em] sm:text-6xl">Due diligence is a decision process—not a scan.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-[#CCE9F8]">Deeptrack combines evidence assessment, risk context, human review, and documentation so teams can make consequential decisions with a clearer record of what they relied on.</p></div></section><section className="mx-auto max-w-[1100px] px-5 py-20 lg:px-10"><div className="grid border-t border-[#D1D1D1] md:grid-cols-2 xl:grid-cols-3">{steps.map(([label, body], index) => <article key={label} className="min-h-56 border-b border-[#D1D1D1] py-8 pr-8 md:border-r md:px-7 xl:nth-[3n]:border-r-0"><span className="text-sm text-[#0191DA]">0{index + 1}</span><h2 className="mt-8 font-[family-name:var(--font-space-grotesk)] text-2xl font-medium">{label}</h2><p className="mt-4 text-sm leading-6 text-[#767676]">{body}</p></article>)}</div></section><section className="bg-[#E6F4FB]"><div className="mx-auto grid max-w-[1100px] gap-12 px-5 py-20 lg:grid-cols-[.8fr_1.2fr] lg:px-10"><div><p className="text-[11px] font-semibold uppercase tracking-[0.16em] text-[#0191DA]">What an assessment produces</p><h2 className="mt-4 font-[family-name:var(--font-space-grotesk)] text-4xl font-medium tracking-[-0.05em]">One workflow. A practical diligence path.</h2></div><div className="grid gap-4 sm:grid-cols-2">{["Risk map and evidence inventory", "Owned review and escalation design", "Decision-record requirements", "Implementation recommendations"].map((item) => <p key={item} className="flex gap-3 bg-white p-5 text-sm leading-6"><Check className="mt-1 shrink-0 text-[#0191DA]" size={16} />{item}</p>)}</div></div></section><section className="mx-auto max-w-[1100px] px-5 py-20 text-center lg:px-10"><h2 className="font-[family-name:var(--font-space-grotesk)] text-4xl font-medium tracking-[-0.05em]">Start with the decision you need to make.</h2><p className="mx-auto mt-5 max-w-xl text-base leading-7 text-[#767676]">We will scope the evidence, risk, owners, and constraints during the discovery conversation.</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 bg-[#0191DA] px-5 py-4 text-sm font-semibold text-white hover:bg-[#003A57]">Request an assessment <ArrowRight size={17} /></Link></section></main><EnterpriseFooter /></div>; }
